### ISSUE TITLE
outdated values

### ISSUE THREAD

**Issue by Darecki626** [mxswat/mx-division-builds#51]
outdated values on future initiative
as for 2 set bonus it says 15% repair skill
while in game is 30%

**Comment by mxswat** [comment]
Really? when did massive change it? 🤔

**Comment by corvidus** [comment]
Issue matches the shot in the announcement made in the FB channel on March 11th this year: 
https://www.facebook.com/TheDivisionGame/photos/the-future-initiative-set-amplifies-repair-skills-skill-haste-duration-making-it/3754375611345001/ 

In the same theme, the 1.36 update included a rework for the Striker's gear set - stacks are now lost at a rate of 2 per second, instead of on missed shots: 
https://discussions.ubisoft.com/topic/124547/completed-maintenance-december-14th-2021/2?lang=en-US

**Comment by Kiochyy** [comment]
Hi

Updated the Future initiative 2p bonus to 30%.

Thanks for your report, I somehow never spotted it.
